In [2]:
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))

import numpy as np
import pandas as pd

from src.path import RAW_DATA_FILE

In [3]:
import pandas as pd
import numpy as np

train_df = pd.read_csv(RAW_DATA_FILE)

train_df.head()

,text,label,prompt_name,source,RDizzl3_seven
0,Phones\n\nModern humans today are always on th...,0,Phones and driving,persuade_corpus,False
1,This essay will explain if drivers should or s...,0,Phones and driving,persuade_corpus,False
2,Driving while the use of cellular devices\n\nT...,0,Phones and driving,persuade_corpus,False
3,Phones & Driving\n\nDrivers should not be able...,0,Phones and driving,persuade_corpus,False
4,Cell Phone Operation While Driving\n\nThe abil...,0,Phones and driving,persuade_corpus,False

Xử lý null & mising data, trùng lập

In [4]:
import re

def clean_text(text):
    text = text.lower()                                  # chuyển chữ thường
    text = re.sub(r'http\S+|www\S+', '', text)            # xóa URL
    text = re.sub(r'\S+@\S+', '', text)                   # xóa email
    text = re.sub(r'<.*?>', '', text)                      # xóa HTML tag nếu có
    text = re.sub(r'[^a-zA-Z0-9\s\.\,\!\?\']', ' ', text)  # giữ lại chữ, số, dấu câu cơ bản
    text = re.sub(r'\s+', ' ', text).strip()               # xóa khoảng trắng thừa
    return text

train_df['text_clean'] = train_df['text'].apply(clean_text)

# Cập nhật lại word_count sau khi làm sạch
train_df['word_count'] = train_df['text_clean'].apply(lambda x: len(x.split()))

train_df[['text', 'text_clean']].head(10)

,text,text_clean
0,Phones\n\nModern humans today are always on th...,phones modern humans today are always on their...
1,This essay will explain if drivers should or s...,this essay will explain if drivers should or s...
2,Driving while the use of cellular devices\n\nT...,driving while the use of cellular devices toda...
3,Phones & Driving\n\nDrivers should not be able...,phones driving drivers should not be able to u...
4,Cell Phone Operation While Driving\n\nThe abil...,cell phone operation while driving the ability...
5,Cell phone use should not be legal while drivi...,cell phone use should not be legal while drivi...
6,Phones and Driving\n\nDriving is a good way to...,phones and driving driving is a good way to ge...
7,PHONES AND DRIVING\n\nIn this world in which w...,phones and driving in this world in which we l...
8,People are debating whether if drivers should ...,people are debating whether if drivers should ...
9,Texting and driving\n\nOver half of drivers in...,texting and driving over half of drivers in to...